###  Global configuration  ###
homeassistant:
  name: Home
  elevation: !secret homeassistant_elevation
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  time_zone: !secret homeassistant_time_zone
  unit_system: metric
  customize: !include include/customize.yaml
  customize_glob: !include include/customize_glob.yaml

http:
  api_password: !secret http_api_password

datadog:
  host: !secret datadog_host
  prefix: home-assistant

homekit:
  auto_start: False
  filter:
    exclude_domains:
      - device_tracker
      - sensor
    exclude_entities:
      - switch.ines_room_lights_switch_2
      - switch.office_lights_switch_2

mqtt:
  broker: mosquitto
  client_id: home-assistant
  discovery: true
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1

recorder:
  purge_keep_days: 5
  exclude:
    domains:
      - group
      - zwave

zwave:
  usb_path: /dev/ttyACM0

### Components ###
config:
conversation:
frontend:
history:
ios:
logbook:
logger:
  default: info
sun:
updater:

### Includes ###
automation: !include automations.yaml
binary_sensor: !include include/binary_sensor.yaml
camera: !include include/camera.yaml
climate: !include include/climate.yaml
cover: !include include/cover.yaml
device_tracker: !include include/device_tracker.yaml
group: !include include/group.yaml
light: !include include/light.yaml
media_player: !include include/media_player.yaml
notify: !include include/notify.yaml
sensor: !include include/sensor.yaml
switch: !include include/switch.yaml
telegram_bot: !include include/telegram_bot.yaml

