- platform: broadlink
  name: Living room AC
  host: !secret climate_living_room_ac_host
  mac: !secret climate_living_room_ac_mac
  ircodes_ini: 'custom_components/gree_ac.ini'
  min_temp: 16
  max_temp: 30
  target_temp: 20
  default_operation: idle
  default_fan_mode: mid
  customize:
    operations:
      - idle
      - cool
      - heat
    fan_modes:
      - low
      - mid
      - high
      - auto
