- platform: kodi
  host: !secret media_player_kodi_host
  port: !secret media_player_kodi_port
  name: Kodi
  user: !secret media_player_kodi_user

- platform: webostv
  host: 192.168.1.253
  name: Living Room TV
